config/routes.rb
Rails.application.routes.draw do
  get 'landingpage/index'

  devise_for :users
  get 'tags/index', as: :tags

  get 'dashboard/'=>'dashboard#show', as: :dashboard

  get 'shared_note/:shared_token' => 'shared_note#show', as: :shared_note
  
  resources :trashed_notes, :only => [:index, :update, :destroy]
  

  resources :notes do 
    get :autocomplete_tag_name, :on => :collection 
  end
  put 'notes/:id/share' => 'notes#share', as: :share_note
  put 'notes/:id/unshare' => 'notes#unshare', as: :unshare_note

  root 'landingpage#index'
  

  

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user, inverse_of: :notes
  validates :title, :presence => true, :length => { :maximum => 250 }
  validates :markdown, :presence => true
  acts_as_taggable
  scope :with_text, ->(text) {where("markdown like :text or title like :text", text: "%#{text}%")}
  scope :active, -> {where(active: true)}
  scope :inactive, -> {where(active: false)}
  scope :most_recent, ->(count=10) {order(updated_at: :desc).limit(count)}

  def share
     self.shared_token = SecureRandom.hex(10)
  end

  def unshare
     self.shared_token = nil
  end

  def throw_away
    self.active = false
  end

  def restore
    self.active = true
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes, inverse_of: :user
  acts_as_tagger
  
  def tags
    self.notes.all_tag_counts.select(:id, :name, 'tags_count as taggings_count')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  def after_sign_in_path_for(resource)
  stored_location_for(resource) || dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @notes = current_user.notes.active.most_recent(10)
    @tags = ActsAsTaggableOn::Tag.most_used(20)#current_user.notes.all_tag_counts.select(:id, :name, 'tags_count as taggings_count').most_used(20)
    @topscore = @tags.first.taggings_count unless @tags.blank?
  end

end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :share, :unshare]
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes.active
    @notes = @notes.active.with_text(params[:search]) unless params[:search].blank?
    @trash_count = current_user.notes.inactive.count
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end
  
  # PUT /note/1/share
  def share
    @note.share
    if @note.save
      redirect_to edit_note_url(@note), notice: 'Note was successfully shared.'
    end
  end
  
  # PUT /note/1/unshare
  def unshare
    @note.unshare
    if @note.save
      redirect_to edit_note_url(@note), notice: 'Note was successfully unshared.'
    end
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.active = true


    respond_to do |format|
      if current_user.notes << @note
        flash[:notice] = 'Note was successfully created.'
        format.html { render :edit }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        flash[:notice] = 'Note was successfully updated.'
        format.html { render :edit }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.active = false
    respond_to do |format|
      if @note.save
        format.html { redirect_to trashed_notes_url, notice: 'Note was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find_by! id: params[:id], active: true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :markdown, :search, :tag_list)
    end
end

app/controllers/shared_note_controller.rb
class SharedNoteController < ApplicationController
  before_action :set_note, only: [:show]
  skip_before_action :authenticate_user!
  def show
    render :layout => false
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find_by_shared_token(params[:shared_token])
    end
    
     # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:shared_token)
    end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all.order(taggings_count: :desc)
    @topscore = ActsAsTaggableOn::Tag.maximum(:taggings_count)

  end

end

app/controllers/trashed_notes_controller.rb
class TrashedNotesController < ApplicationController
  before_action :set_note, only: [:update, :destroy]
  
  def index
    @notes = current_user.notes.inactive
  end

  def update
    @note.active = true
    if @note.save
      redirect_to trashed_notes_url(), notice: 'Note was successfully restored.'
    end
  end

  def destroy
    if @note.destroy
      redirect_to trashed_notes_url(), notice: 'Note was successfully destroyed.'
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.inactive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def darkened_tag (tag)
    highscore = @tags.first.taggings_count.to_d
    myscore = tag.taggings_count.to_d
    ratio = (myscore**5 / highscore**5)#(myscore**highscore / highscore) / (highscore**highscore / highscore)
    saturation = (ratio) * 10 + 70
    lightness = (1 - ratio) * 50 + 20
    whiteText = "color:white;" unless lightness >= 70
    render html: "<span class=\"tag\" style=\"color:white;background:hsl(220, #{saturation}%, #{lightness}%)\" data-tag-count=\"#{myscore}\">#{tag.name}</span>".html_safe
  end
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/helpers/notes_helper.rb
module NotesHelper
    def link_to_shared
        if @note.shared_token.blank?
            "not shared"
        else
            link_to shared_note_url(@note.shared_token), shared_note_url(@note.shared_token)
        end
    end
    
    def link_to_toggle_share
        if @note.shared_token.blank?
            link_to '', share_note_path(@note), class: "action-item fa fa-share-square-o", method: :put
        else 
            link_to 'Unshare', unshare_note_path(@note), method: :put
        end
    end
end

app/helpers/shared_note_helper.rb
module SharedNoteHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/trashed_notes_helper.rb
module TrashedNotesHelper
end

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>
<div id="dashboard">
  <div class="section">
    <%= link_to "New Note", new_note_path %>
    <%= form_tag notes_path, method: :get, id: "search_form" do %>
      <%= text_field_tag :search %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
  
  <% if @notes.blank? %>
    <div class="section">
      <h3>You don't have any notes! Create a note by clicking on the New Note button above.</h3>
    </div>
  <% else %>
    <div id="recent_notes" class="section">
      <h3>Recent Notes</h3>
      <table id="note_list">
        <thead>
          <tr>
            <th>Title</th>
            <th>Last Updated</th>
          </tr>
        </thead>
        
        <tbody>
          <% @notes.each do |note| %>
            <tr>
              <td><%= link_to note.title, edit_note_path(note) %></td>
              <td><%= note.updated_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
  <div id="all_notes" class="all-items">
  <%= link_to "All Notes", notes_path%>
  </div>
  
  <% end %>
  
  <div id="tag_list" class="section">
    <h3>Most Used Tags</h3>
    <%= render partial: 'tags/show', collection: @tags, as: :tag, locals: {topscore:@topscore} %>
  </div>
  
  <div id="all_tags" class="all-items">
    <%= link_to "All Tags", tags_path %>
  </div>
</div>

app/views/landingpage/index.html.erb
<%= image_tag 'LightbulbLogo.png', :alt => 'LightBulb' %> 
<h3>Example:</h3>
<%= image_tag 'lightbulb_screen_capture.png', :alt => 'LightBulb Example', :class => "style_example_image" %> 
<h1>Welcome to Lightbulb!</h1>
<form action="/users/sign_up" id="SignUp">
    <input type="submit" value="Sign Up"> 
</form>
<div>Or</div>
<form action="/users/sign_in" id="SignIn">
    <input type="submit" value="Log In">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Lightbulb</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= image_tag 'logo.png', :alt => 'LightBulb', :class => 'logo' %> 
    <%= link_to 'Dashboard', dashboard_path, class: 'dashboard' %>
    <%= link_to "New Note", new_note_path %>
    <%= link_to 'Trash Can', trashed_notes_path %>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>


    <% if user_signed_in? %>
      <div>Signed in as <%= link_to current_user.email, edit_user_registration_path %></div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @note.created_at.blank? %>
    <div class="field">
      <div class="meta">Created: <%= @note.created_at %></div>
      <div class="meta">Last Update: <%= @note.updated_at %></div>
      <div class="meta">Sharing: <%=link_to_shared %></div>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, maxLength: 250 %>
  </div>
  
  <div class="field">
    <%= f.label :tag_list, "Tags* (seperated by commas)" %><br>
    <%= f.autocomplete_field :tag_list, autocomplete_tag_name_notes_path, 'data-delimiter' => ', ', value: @note.tag_list.join(", ")%>
  </div>
  
  <div class="markdown">
    <%= f.label :markdown %><br>
    <%= f.text_area :markdown %>
  </div>
  
  <div id="compiled" class="markdown">
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>Editing Note</h1>


<%= link_to '', notes_path, class: "action-item fa fa-arrow-left" %> |
<%= link_to_toggle_share %> |

<%= link_to '', @note, method: :delete, data: { confirm: 'Are you sure?' }, class: "action-item fa fa-trash-o" %>
<%= render 'form' %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table id="note_list">
  <thead>
    <tr>
      <th class="note title">Title</th>
      <th class="note last-update">Last Updated</th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td class="note title"><%= link_to note.title, edit_note_path(note), class: "titleTable" %></td>
        <td class="note last-update"><%= note.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %> |
<%= link_to "Trash Can (#{@trash_count})", trashed_notes_path(@note) %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Markdown:</strong>
  <%= @note.markdown %>
</p>
<p>
  <strong>Tags:</strong>
  <%= @note.tags %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/shared_note/show.html.erb
<% unless @note.blank? %>

<%= hidden_field_tag :markdown, @note.markdown %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


<div id="compiled" class="markdown">
</div>
<p>This note was created using the Lightbulb Markdown Editor. <br>
If you would like to create your own markdown please visit 
<%= link_to "Lightbulb.io", root_path %>
</p>

<% else %>
    <h1>This note has been unshared or doesn't exist.</h1>
<% end %>

app/views/tags/_show.erb
<%
  topscore = topscore.to_d
  myscore = tag.taggings_count.to_d
  ratio = (myscore**5 / topscore**5)#(myscore**highscore / highscore) / (highscore**highscore / highscore)
  saturation = (ratio) * 10 + 70
  lightness = (1 - ratio) * 50 + 20
  whiteText = "color:white;" unless lightness >= 70
%>
<a href="#" class="tag" style="color:white;background:hsl(220, <%= saturation %>%, <%= lightness %>%)" data-taggings-count="<%= myscore.to_i %>"><%= tag.name %></a>

app/views/tags/index.html.erb
<h1>Listing Tags</h1>

<%= render partial: 'tags/show', collection: @tags, as: :tag, locals: {topscore:@topscore} %>

app/views/trashed_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trash Can</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Restore</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= link_to 'Restore', trashed_note_url(note), method: :put, data: { confirm: 'Are you sure you want to restore?' }%> | </td>
        <td><%= link_to 'Delete', trashed_note_url(note), method: :delete, data: { confirm: 'Are you sure you want to delete?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back To Note List', notes_path %>